#pragma once
#include "pcb.h"

class CPUScheduling
{
private:
	PCB* RUNNING;				//WSKAèNIK DO BLOKU PCB W£AåNIE WYKONYWANEGO
	PCB* NEXTTRY;				//WSKAèNIK DO BLOKU PCB, KT”RY ZAWIADOWCA B DZIE STARA£ SI  USTAWI∆ JAKO NAST PNY = RUNNING->NEXT_PCB_ALL
	bool NEXTTRY_MODIFIED;		//R”WNY ZERU, JEåLI WSKAèNIK NEXTTRY NIE ZMIANIA£ SI  OD CHWILI NADANIA MU WARTOåCI PRZEZ ZAWIADOWC 


public:
	CPUScheduling();
	
	PCB* get_RUNNING();
	PCB* get_NEXTTRY();
	void set_NEXTTRY(PCB* new_NEXTTRY);

};