#pragma once

struct PCB;
struct Semaphore
{
	int VALUE; //WARTOå∆ SEMAFORA. WYKONANIE OPERACJI 'P' POWODUJE ODJ CIE JEDYNKI OD WARTOåCI, A 'V' DODANIE
	PCB* FIRST_WAITER; //WSKAèNIK DO PIERWSZEGO BLOKU PCB NA LIåCIE BLOK”W ZE SOB• PO£•CZONYCH ZA POMOC• WSKAèNIK”W 'NEXT_SEMAPHORE_WAITER'

	Semaphore(int val, PCB* first_waiter)
		:VALUE(val), FIRST_WAITER(first_waiter)
	{}
};